"""Download the viewer's webfonts once and inline them as base64 into a CSS file.

**Why this exists.** ``docs/index.html`` used to pull Archivo and IBM Plex Mono from
``fonts.googleapis.com`` at render time, while the README promised a page with "no
server and no network". Opened the way a reviewer actually opens it -- a local file,
possibly offline -- every face fell back to the system UI font and the page's whole
type system collapsed. The design was never the problem; the missing fonts were.

So the fonts are fetched **here, once**, committed as ``scripts/fonts/fonts.css`` with
the ``woff2`` payloads inlined as ``data:`` URIs, and read from disk by
``build_viewer.py``. That keeps the viewer build offline and deterministic, which
matters because ``tests/test_viewer.py`` byte-compares the committed page against a
fresh build -- a build that reached for the network would be neither.

Only the ``latin`` and ``latin-ext`` subsets are kept. ``latin-ext`` is not optional:
the rupee sign U+20B9 lives in it, and it is on almost every line of this page.

Both families are SIL Open Font License 1.1, which permits redistribution; the licence
notice is written into the generated CSS.

    python scripts/fetch_fonts.py

Re-run only to change the weights or families. Day to day, the committed CSS is the
input and this script is documentation of where it came from.
"""

from __future__ import annotations

import base64
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "fonts" / "fonts.css"

API = (
    "https://fonts.googleapis.com/css2"
    "?family=Archivo:wght@400;600;700"
    "&family=IBM+Plex+Mono:wght@400;600"
    "&display=swap"
)

# Google serves woff2 only to a UA it believes supports it.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# The two subsets the page can actually render text in. Identified by a codepoint that
# is unique to each range, rather than by the comment Google happens to emit above it.
LATIN = "U+0000-00FF"
LATIN_EXT = "U+2C60-2C7F"

LICENCE = """/* Archivo and IBM Plex Mono, SIL Open Font License 1.1.
   Generated by scripts/fetch_fonts.py -- do not hand-edit.
   Inlined as base64 so docs/index.html renders identically with no network. */
"""


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def main() -> int:
    css = fetch(API).decode("utf-8")
    faces = re.findall(r"@font-face\s*\{[^}]*\}", css)
    if not faces:
        print("no @font-face blocks returned; the API shape changed", file=sys.stderr)
        return 1

    kept: list[str] = []
    for face in faces:
        ranges = re.search(r"unicode-range:\s*([^;]+);", face)
        if not ranges or not (LATIN in ranges.group(1) or LATIN_EXT in ranges.group(1)):
            continue
        url_match = re.search(r"url\((https://[^)]+\.woff2)\)", face)
        if not url_match:
            continue
        payload = fetch(url_match.group(1))
        data_uri = f"data:font/woff2;base64,{base64.b64encode(payload).decode('ascii')}"
        kept.append(face.replace(url_match.group(1), data_uri))
        family = re.search(r"font-family:\s*'([^']+)'", face)
        weight = re.search(r"font-weight:\s*(\d+)", face)
        print(
            f"  {family.group(1) if family else '?':<16}"
            f"{weight.group(1) if weight else '?':>5}  {len(payload):>7,} bytes"
        )

    if not kept:
        print("no latin faces matched; nothing written", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(LICENCE + "\n" + "\n".join(kept) + "\n", encoding="utf-8")
    print(f"\nwrote {OUT}  ({OUT.stat().st_size:,} bytes, {len(kept)} faces)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
